# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{twiq}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["tily"]
  s.date = %q{2010-11-13}
  s.default_executable = %q{twiq}
  s.description = %q{simple queue system for twitter}
  s.email = %q{tily05@gmail.com}
  s.executables = ["twiq"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "bin/twiq",
     "lib/twiq.rb",
     "lib/twiq/commands.rb",
     "lib/twiq/statuses.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/twiq_commands_speq.rb"
  ]
  s.homepage = %q{http://github.com/tily/ruby-twiq}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{simple queue system for twitter}
  s.test_files = [
    "spec/twiq_commands_speq.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<sequel>, [">= 0"])
      s.add_runtime_dependency(%q<oauth-cli-twitter>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<sequel>, [">= 0"])
      s.add_dependency(%q<oauth-cli-twitter>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<sequel>, [">= 0"])
    s.add_dependency(%q<oauth-cli-twitter>, [">= 0"])
  end
end

